# Generated by Django 3.2.3 on 2021-05-28 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.TextField()),
                ('title', models.TextField()),
                ('subject', models.TextField()),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('private', models.BooleanField(db_index=True, default=False)),
            ],
        ),
        migrations.AddIndex(
            model_name='flashcard',
            index=models.Index(condition=models.Q(('private', False)), fields=['private'], name='public_flashcards_index'),
        ),
    ]
